version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: glasschat-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - glasschat-network

  # Optional: Redis Commander for Redis management UI
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: glasschat-redis-ui
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - glasschat-network
    profiles:
      - tools # Only start with: docker-compose --profile tools up

volumes:
  redis_data:
    driver: local

networks:
  glasschat-network:
    driver: bridge 